SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += $(PWD)/../../Designs/design_2/design_2.v

TOPLEVEL = design_2
MODULE = test_design_2

include $(shell cocotb-config --makefiles)/Makefile.sim
