SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += $(PWD)/../../Designs/design_3/design_3.v

TOPLEVEL = design_3
MODULE = test_design_3

include $(shell cocotb-config --makefiles)/Makefile.sim
